language: python
required: sudo
python:
    "2.7"
virtualenv:
    system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - sudo apt-get install python-tk
  - python -m pip install nose coverage codecov mock
script:
  - python -m pip install .
  - python -m nose
after_success:
  - coverage run nosetests
  - codecov
